// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacApp_Bovinova_Platform.Shared.Infrastructure.Persistence.EFC.Configuration;

#nullable disable

namespace VacApp_Bovinova_Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VacApp_Bovinova_Platform.AIAssistant.Domain.Model.Entities.BovineAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine_id");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created-at");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendation");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("score");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("urgency-level");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("VisibleIssues")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("visible-issues");

                    b.HasKey("Id")
                        .HasName("p-k_bovine-analyses");

                    b.ToTable("bovine-analyses");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.AIAssistant.Domain.Model.Entities.BovineChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created-at");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messages-json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated-at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_bovine-chat-sessions");

                    b.ToTable("bovine-chat-sessions");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.AIAssistant.Domain.Model.Entities.GeneralChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created-at");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messages-json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated-at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_general-chat-sessions");

                    b.ToTable("general-chat-sessions");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.AlertManagement.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("alert_type");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("urgency_level");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_alerts");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.CampaignManagement.Domain.Model.Aggregates.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end-date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start-date");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_campaigns");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created-at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("subscription-plan");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated-at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p-k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IoTMonitoring.Domain.Model.Aggregates.BovineHealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("int")
                        .HasColumnName("battery_level");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device-id");

                    b.Property<float>("HeartRate")
                        .HasColumnType("float")
                        .HasColumnName("heart-rate");

                    b.Property<bool>("IsAlert")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is-alert");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded-at");

                    b.Property<float>("Temperature")
                        .HasColumnType("float")
                        .HasColumnName("temperature");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_bovine-health-records");

                    b.HasIndex("BovineId")
                        .HasDatabaseName("i-x_bovine-health-records_bovine_id");

                    b.ToTable("bovine-health-records");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IoTMonitoring.Domain.Model.Aggregates.Collar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BovineId")
                        .HasColumnType("int")
                        .HasColumnName("bovine_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lifecycle_status");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("registered_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_collars");

                    b.HasIndex("BovineId")
                        .HasDatabaseName("i-x_collars_bovine_id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("i-x_collars_device_id");

                    b.ToTable("collars");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("birth-date");

                    b.Property<string>("BovineImg")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("bovine-img");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("breed");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<int>("MaxHeartRate")
                        .HasColumnType("int")
                        .HasColumnName("max-heart-rate");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("double")
                        .HasColumnName("max-temperature");

                    b.Property<int>("MinHeartRate")
                        .HasColumnType("int")
                        .HasColumnName("min-heart-rate");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("double")
                        .HasColumnName("min-temperature");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("StableId")
                        .HasColumnType("int")
                        .HasColumnName("stable-id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_bovines");

                    b.HasIndex("StableId")
                        .HasDatabaseName("i-x_bovines_stable-id");

                    b.ToTable("bovines");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user-id");

                    b.HasKey("Id")
                        .HasName("p-k_categories");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category-id");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration-date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext")
                        .HasColumnName("unit");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user-id");

                    b.HasKey("Id")
                        .HasName("p-k_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i-x_products_category-id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Stable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Limit")
                        .HasColumnType("int")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_stables");

                    b.ToTable("stables");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.Aggregates.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_staff");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.SubscriptionManagement.Domain.Model.Aggregates.AdditionalCollarRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created-at");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monthly_amount");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated-at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_additional-collar-requests");

                    b.ToTable("additional-collar-requests");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.SubscriptionManagement.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created-at");

                    b.Property<DateTime?>("NextRenewal")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_renewal");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plan");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("suspended-at");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated-at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p-k_subscriptions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i-x_subscriptions_user_id");

                    b.ToTable("subscriptions");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IoTMonitoring.Domain.Model.Aggregates.BovineHealthRecord", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", null)
                        .WithMany()
                        .HasForeignKey("BovineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_bovine-health-records_-bovine_bovine_id");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.IoTMonitoring.Domain.Model.Aggregates.Collar", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", null)
                        .WithMany()
                        .HasForeignKey("BovineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_collars_-bovine_bovine_id");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Bovine", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Stable", "Stable")
                        .WithMany()
                        .HasForeignKey("StableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_bovines_-stable_stable-id");

                    b.Navigation("Stable");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Product", b =>
                {
                    b.HasOne("VacApp_Bovinova_Platform.RanchManagement.Domain.Model.Aggregates.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f-k_products_categories_category-id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.Aggregates.Staff", b =>
                {
                    b.OwnsOne("VacApp_Bovinova_Platform.StaffAdministration.Domain.Model.ValueObjects.EmployeeStatus", "EmployeeStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("employee_status");

                            b1.HasKey("Id")
                                .HasName("p-k_staff");

                            b1.ToTable("staff");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f-k_staff_staff_id");
                        });

                    b.Navigation("EmployeeStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
